name: Magisk Build

on:
  push:
    branches: [master]
    paths:
      - "app/**"
      - "native/**"
      - "build.py"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build WeaveMask artifacts
    runs-on: macos-26
    strategy:
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Auto-Fix API Mismatch
        # هذا السطر يبحث عن الدالة القديمة ويستبدلها بالجديدة تلقائياً لتجنب خطأ Rust
        run: |
          sed -i '' 's/generate_header_and_cc_with_path/generate_header_and_cc/g' native/src/base/include/codegen.rs || echo "Already fixed or file not found"

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          is-asset-build: true

      - name: Build release
        run: python3 build.py -vr all

      - name: Stop gradle daemon
        run: ./app/gradlew --stop

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.sha }}
          path: out
          compression-level: 9

      - name: Upload mapping and native debug symbols
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.sha }}-symbols
          path: app/apk/build/outputs
          compression-level: 9
