name: Magisk Build

on:
  push:
    branches: [master]
    paths:
      - "app/**"
      - "native/**"
      - "build.py"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build WeaveMask artifacts
    runs-on: macos-26
    strategy:
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Force Update Submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --force --remote
          # التأكد من وجود المجلد المطلوب وإصلاحه في حال كان فارغاً
          if [ ! -f "native/src/external/cxx-rs/Cargo.toml" ]; then
            echo "Submodule cxx-rs is missing, attempting manual fix..."
            git clone https://github.com/dtolnay/cxx native/src/external/cxx-rs
          fi

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          is-asset-build: true

      - name: Build release
        run: python3 build.py -vr all

      - name: Stop gradle daemon
        run: ./app/gradlew --stop

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.sha }}
          path: out
          compression-level: 9

      - name: Upload mapping and native debug symbols
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.sha }}-symbols
          path: app/apk/build/outputs
          compression-level: 9
